os: linux
dist: trusty
sudo: required
language: ruby

services:
  - docker
  - mysql
  - postgresql
  - redis-server

addons:
  apt:
    packages:
    - mysql-server-5.5
    - mysql-client-5.5
    - mysql-client-core-5.5

rvm:
  - 2.3.1
  - 2.2.5

env:
  global:
    - DB=sqlite
    - BASEOS_IMAGE=codestand/baseos@sha256:d3effd3cea63fdee81a07532087e7081d383f71bf4300d6140eaeccde7d23b9c

matrix:
  include:
    - env: DB=postgresql
    - env: DB=mysql
  allow_failures:
    - env: BASEOS_IMAGE=codestand/baseos:latest

cache:
  directories:
    - vendor/bundle

before_install:
  - sudo apt-get install -y mysql-server mysql-client
  - cp ci/database.$DB.yml config/database.yml
  - psql  -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;' -u root

install:
  - bundle install --jobs 2 --path vendor/bundle

before_script:
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - "CODECLIMATE=true bundle exec rspec"
